backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections: 
  - label: "Configuration"
    name: "config"
    files:
      - label: "Site configuration"
        name: "site-config"
        file: "src/configuration/site.json"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Disclaimer, name: disclaimer, widget: string}
          - {label: Phone, name: phone, widget: string}
          - {label: E-mail, name: email, widget: string}
          - label: Address
            name: address
            widget: object
            fields: 
            - {label: "Name", name: "name", widget: "string"}
            - {label: "Street", name: "street", widget: "string"}
            - {label: "City", name: "city", widget: "string"}
            - {label: "Postal Code", name: "zip", widget: "string"}
  - label: "Pages"
    name: "pages"
    files:
      - label: "About us page"
        name: "about-us"
        file: "src/content/about-us.md"
        fields: 
          - {label: Key, name: key, widget: hidden, default: "about-us"}
          - {label: Title, name: title, widget: string}
          - {label: Path, name: path, widget: hidden, default: "/o-nas/"}
          - {label: "Show in menu", name: showInMenu, widget: boolean, default: true}
          - {label: Content, name: body, widget: markdown}
      - label: "Services page"
        name: "services"
        file: "src/content/services.md"
        fields: 
          - {label: Key, name: key, widget: hidden, default: "services"}
          - {label: Title, name: title, widget: string}
          - {label: Path, name: path, widget: hidden, default: "/sluzby/"}
          - {label: "Show in menu", name: showInMenu, widget: boolean, default: true}
          - {label: Content, name: body, widget: markdown}
      - label: "Team"
        name: "team"
        file: "src/content/team.json"
        fields:
          - {label: Key, name: key, widget: hidden, default: "team"}
          - {label: Title, name: title, widget: string, defualt: "Tým"}
          - {label: Path, name: path, widget: hidden, default: "/tym/", }
          - {label: "Show in menu", name: showInMenu, widget: boolean, default: true}
          - label: "Team Members"
            name: "teamMembers"
            widget: list
            fields:
              - {label: Name, name: name, widget: string}
              - {label: Photo, name: photo, widget: image}
              - {label: Specialization, name: specialization, widget: string}
              - {label: Bio, name: bio, widget: markdown}
