backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections: 
  - label: "Configuration"
    name: "config"
    files:
      - label: "Site configuration"
        name: "site-config"
        file: "src/configuration/site.json"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Disclaimer, name: disclaimer, widget: string}
          - {label: Phone, name: phone, widget: string}
          - {label: E-mail, name: email, widget: string}
          - label: Address
            name: address
            widget: object
            fields: 
            - {label: "Name", name: "name", widget: "string"}
            - {label: "Street", name: "street", widget: "string"}
            - {label: "City", name: "city", widget: "string"}
            - {label: "Postal Code", name: "zip", widget: "string"}
  - label: "Pages"
    name: "pages"
    files:
      - label: "About us page"
        name: "about-us"
        file: "src/content/about-us.md"
        fields: 
          - {label: Key, name: key, widget: hidden, default: "about-us"}
          - {label: Title, name: title, widget: string}
          - {label: Content, name: body, widget: markdown}
      - label: "Services page"
        name: "services"
        file: "src/content/services.md"
        fields: 
          - {label: Key, name: key, widget: hidden, default: "services"}
          - {label: Title, name: title, widget: string}
          - {label: Content, name: body, widget: markdown}
      - label: "Price list page"
        name: "pricelist"
        file: "src/content/pricelist.md"
        fields: 
          - {label: Key, name: key, widget: hidden, default: "pricelist"}
          - {label: Title, name: title, widget: string}
          - {label: Content, name: body, widget: markdown}
